### PR TITLE
Lesson11

### PR DESCRIPTION
**Pull request by Derhanov**

### CODE REVIEW

**Comment by Yanko-Svitlana** [comment]
Add select in form on the contact-us page.

**Comment by Yanko-Svitlana** [comment]
Change background in fotter-form

**Comment by Yanko-Svitlana** [comment]
Add dropdown-menu in top-nav

**Comment by Yanko-Svitlana** [comment]
Add clossed quotes to the testimonial-page

**Comment by Yanko-Svitlana** [comment]
on the testimonial-page replace container

**Comment by Yanko-Svitlana** [comment]
on the blog-post page remote input field "service"

**Comment by RuslanYurchenko** [comment]
You should review and leave comments directly in the "file changed" tab, not in the 'conversation'.  Maybe I'm wrong.

**Comment by RuslanYurchenko** [comment]
You should review and leave comments directly in the "file changed" tab, not in the 'conversation'. Maybe I'm wrong.

**Pull request closed without merging**
